<Project>

  <PropertyGroup>
    <Version>0.0.1</Version>

    <Authors>Ronald Schlenker</Authors>
    <Copyright>Copyright 2025 Ronald Schlenker</Copyright>
    <PackageTags>f# fsharp signal stream dsp stateful reactive computation-expression</PackageTags>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/fsprojects/LocSta</RepositoryUrl>
    <Description>Stateful signal processing and stream computation library for F#</Description>
  </PropertyGroup>

</Project>
