<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Types.fs" />
    <Compile Include="BlockSources.generated.fs" />
    <Compile Include="BlockDemos.fs" />
    <Compile Include="SvgChart.fs" />
    <Compile Include="Render.fs" />
    <Compile Include="App.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LocSta2\LocSta2.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Fable.Core" Version="4.*" />
    <PackageReference Include="Fable.Browser.Dom" Version="2.*" />
    <PackageReference Include="Fable.Browser.Event" Version="1.*" />
  </ItemGroup>

</Project>
