// Reads all .fs block source files from src/LocSta2/ and generates
// src/demoSite/BlockSources.generated.fs with a Map<string, string>
// from block name to source code. Run before Fable compilation.

import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, basename, extname } from "node:path";

const LIB_DIR = "src/LocSta2";
const OUT_FILE = "src/demoSite/BlockSources.generated.fs";
const EXCLUDE = new Set(["Core.fs", "Blocks.fs"]);

async function findFsFiles(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  const results = [];
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      results.push(...(await findFsFiles(full)));
    } else if (
      entry.name.endsWith(".fs") &&
      !entry.name.endsWith(".fsproj") &&
      !EXCLUDE.has(entry.name)
    ) {
      results.push(full);
    }
  }
  return results;
}

function escapeFs(s) {
  return s
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "");
}

async function main() {
  const files = await findFsFiles(LIB_DIR);
  files.sort();

  const entries = [];
  for (const file of files) {
    const name = basename(file, extname(file));
    const content = await readFile(file, "utf-8");
    entries.push(`          ("${name}", "${escapeFs(content)}")`);
  }

  const module = [
    "// Auto-generated by scripts/extract-sources.mjs — do not edit",
    "module DemoSite.BlockSources",
    "",
    "let sources =",
    "    Map.ofList",
    "        [" + (entries.length > 0 ? "" : " ]"),
    ...entries.map((e, i) => e + (i < entries.length - 1 ? "" : " ]")),
  ].join("\n") + "\n";

  await writeFile(OUT_FILE, module, "utf-8");
  console.log(`Generated ${OUT_FILE} with ${entries.length} block sources.`);
}

main();
